Add standardized point cloud time processing
norlab-ulaval/libpointmatcher_ros pull request #5
Opened 2024-12-20 19:04 UTC by boxanm

The time field from ROS messages is always converted to the libpointmatcher "time" field of int64. The code that handles the conversion from different lidar types was originally located in the `pointcloud_motion_deskew` package.

Tested on:

- Ouster-like lidar (RS-32)
- Velodyone-like lidar (LS-128)
- Hesai-like lidar (RS-128)

2025-01-05 20:37 UTC, simonpierredeschenes commented on README.md
> +For Hesai-like timestamps, the timestamp is stored in the `double` field `timestamp` in the ROS message.
There is no double field type in PointCloud2 messages, I believe it is Float64.

2025-01-05 20:39 UTC, simonpierredeschenes commented on src/PointMatcher_ROS.cpp
> +			isFeature.push_back(false);
line 64 seems to be a duplicate of line 65

2025-01-05 20:48 UTC, simonpierredeschenes requested changes
Good job @boxanm! Minor changes are needed, but the PR can be merged once they are fixed.

2025-01-05 22:49 UTC, boxanm commented on src/PointMatcher_ROS.cpp
> +			isFeature.push_back(false);
It is not; the reason for this is that we process `_splitTime_low32` and `_splitTime_high32` at once.

2025-01-06 03:31 UTC, simonpierredeschenes approved these changes

2025-01-28 02:33 UTC, merged